# Create a 1D NumPy array with 15 evenly spaced numbers between 5 and 25.

In [1]:
import numpy as np

In [2]:
a=np.linspace(5,25,15)
print(a)

[ 5.          6.42857143  7.85714286  9.28571429 10.71428571 12.14285714
 13.57142857 15.         16.42857143 17.85714286 19.28571429 20.71428571
 22.14285714 23.57142857 25.        ]


#  Generate a 4x4 matrix filled with random integers between 50 and 100.

In [3]:
b=np.random.randint(50,100,(4,4))
print(b)

[[88 88 87 76]
 [95 85 81 66]
 [53 76 59 80]
 [81 78 62 60]]


 # Create a NumPy array of ones with a shape of (3, 4).

In [4]:
a=np.arange(1,13)
b=a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Create a 1D array of 10 random numbers and multiply each element by 2.

In [5]:
a=np.random.randint(10,size=10)
print(a)
print(a*2)


[0 1 2 2 8 4 5 6 1 7]
[ 0  2  4  4 16  8 10 12  2 14]


#  Generate a 2D array of shape (6, 3) filled with random floating-point numbers between 0 and 1.


In [6]:
a=np.random.random((6,3))
a

array([[0.95372827, 0.01082618, 0.31470768],
       [0.22698436, 0.11179055, 0.63066788],
       [0.13016705, 0.50292145, 0.26498854],
       [0.01433741, 0.50029166, 0.15200739],
       [0.50979859, 0.6323323 , 0.81559531],
       [0.45825327, 0.36052865, 0.62479911]])

In [7]:
a = np.random.uniform(0, 1, (6, 3))
print(a)


[[0.55811695 0.97580842 0.17658978]
 [0.60572443 0.58410947 0.52407099]
 [0.27151567 0.16059942 0.00378234]
 [0.91066915 0.1900988  0.86236524]
 [0.39734157 0.43699212 0.7262199 ]
 [0.45531095 0.4732595  0.24836053]]


#  Given the array arr = np.arange(1, 21).reshape(5, 4)
   - The first column
 
   - The third row
   
   - A sub-matrix consisting of rows 2 and 3, and columns 1 to 2
   

In [8]:
arr=np.arange(1,21).reshape(5,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [9]:
print(arr[:,0])
print(arr[2])
print(arr[1:3,1:3])

[ 1  5  9 13 17]
[ 9 10 11 12]
[[ 6  7]
 [10 11]]


# Create an array arr = np.arange(10, 31).reshape(7, 3)
   - The element at position (2, 1)
   
   - The last 3 elements of the second column:
    
   - The elements in the first and third columns of the last two rows
    

In [10]:
arr=np.arange(10,31).reshape(7,3)
print(arr)
print(arr[2][1])
print(arr[2])
print(arr[5:,0::2])

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]
17
[16 17 18]
[[25 27]
 [28 30]]


 # Slice a 1D array to retrieve every third element starting from index 0.

In [11]:
ary=np.arange(10)
ary[0::3]=0
print(ary)

[0 1 2 0 4 5 0 7 8 0]


# Create a 1D NumPy array of integers from 1 to 20 

   - Calculate the square of each element
  
   - Subtract 5 from each element

In [12]:
a=np.arange(1,20)
print(a)
print(a**2)
print(a-5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
[-4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Given an array arr = np.array([2, 3, 4, 5])

- The exponential of each element
     
- The logarithm base 2 of each element

In [13]:
a=np.array([2,3,4])
b=np.exp(a)
c=np.log2(a)
print('The exponential of each element',b)
print('The logarithm base 2 of each element',c)

The exponential of each element [ 7.3890561  20.08553692 54.59815003]
The logarithm base 2 of each element [1.        1.5849625 2.       ]


#  Create a NumPy array of integers from 1 to 10 
- The factorial of each element
     
- The sine of each element (in radians)

In [14]:
from scipy.special import factorial
n=np.arange(1,10)
print(n)
a=factorial(n,exact=True)
print(a)


[1 2 3 4 5 6 7 8 9]
[     1      2      6     24    120    720   5040  40320 362880]


# Create an array arr = np.random.randint(1, 100, 50) and filter all numbers
   that are divisible by both 3 and 5.

In [15]:
arr = np.random.randint(1, 100, 50)
arr[(arr%3==0) & (arr%5==0)]
print(arr)

[54  9 18 33  5 30 29 78 94 15 44 22 27 60 96 19 51 19 33 50 60 82 34 17
 46 25 22 63 30 83 47 11 54 63 45 26 72 65 16 78 59 69 49 53 65 45 87 87
 19 18]


# Create a 2D array of shape (4, 5) with values from 1 to 20 and reshape it into a 2D array of shape (5, 4).

In [16]:
ar=np.arange(1,21).reshape(4,5)
print(ar)
b=np.transpose(ar)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


#  Create a 3x3 identity matrix using NumPy.

In [18]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
