# Create a 1D NumPy array of size 10 filled with zeros.

In [1]:
import numpy as np

In [2]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Create a 1D NumPy array of size 10 filled with ones.

In [3]:
a=np.ones(10,dtype=int)
print(a)

[1 1 1 1 1 1 1 1 1 1]


# Create a 1D array of numbers from 0 to 9.

In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


# Create a 1D array of numbers from 5 to 15.

In [5]:
a=np.arange(5,16)
print(a)

[ 5  6  7  8  9 10 11 12 13 14 15]


# Create an array of 10 numbers equally spaced between 0 and 1

In [6]:
a=np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [7]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create a 5×5 matrix filled with the number 7.

In [8]:
a=np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

# Create an array of 15 random integers between 1 and 50.

In [9]:
a=np.random.randint(1,50,15)
print(a)

[39 33 44 33 32 21 29 23 29 12  2 14  1 34 47]


# Create a 2×3 matrix of random floats between 0 and 1.

In [11]:
a=np.random.rand(2,3)
print(a)

[[0.02857557 0.98500481 0.90073454]
 [0.85155322 0.71750803 0.72619927]]


# Create a 3D array of shape 2×3×4 filled with ones.

In [12]:
a=np.ones((2,3,4))
print(a)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# Find the shape of a given arra

In [13]:
a=np.ones((2,3,4))
print(a)
print(a.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)


# Find the total number of elements in an array.

In [14]:
ar=np.arange(1,21).reshape(4,5)
print(ar.size)

20


# Find the number of dimensions of an array.

In [15]:
ar=np.arange(1,21).reshape(4,5)
print(ar.ndim)

2


# Find the data type of an array.

In [16]:
ar=np.arange(1,21).reshape(4,5)
print(ar.dtype)

int32


# Find the number of dimensions of an array.

In [ ]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(a.ndim)

# Find the total number of elements in an array.

In [17]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(a.size)

9


# Find the data type of an array.

In [18]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(a.dtype)

int32


# Change the data type of an array from int to float.

In [20]:
a=np.array([[1,2,3],[3,4,5],[6,7,8]])
b=a.astype(bool)
print(b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# Reshape a 1D array of 12 elements into a 3×4 array.

In [21]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Flatten a 2D array into a 1D array.

In [22]:
a=np.arange(12).reshape(3,4)
b=a.flatten()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# Transpose a 3×4 matrix.

In [23]:
a=np.arange(12).reshape(3,4)
print(a)
b=a.transpose()
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Create a 3D array and find its shape, ndim, and size.

In [24]:
a=np.random.randint(1,10,(2,3,4))
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[[6 3 3 2]
  [5 5 3 4]
  [7 8 3 9]]

 [[6 7 8 8]
  [9 1 9 8]
  [4 1 9 5]]]
(2, 3, 4)
3
24


# Convert a Python list to a NumPy array.

In [25]:
a=[1,2,3,4,5,6]
b=np.array(a)
print(b)
print(type(b))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# Access the first element of an array.

In [35]:
a=np.array([1,2,3,4,5])
print(a)
a[0:3]


[1 2 3 4 5]


array([1, 2, 3])

# Access the last element of an array.

In [36]:
a=np.array([1,2,3,4,5])
print(a)
a[-1]

[1 2 3 4 5]


5

# Access a specific row of a 2D array.

In [37]:
a=np.random.randint(1,10,(5,5))
print(a)
a[1]

[[2 4 7 2 6]
 [8 4 3 2 7]
 [7 5 9 5 6]
 [1 6 5 2 2]
 [6 8 4 1 8]]


array([8, 4, 3, 2, 7])

# Access a specific column of a 2D array.

In [39]:
a=np.random.randint(1,10,(5,5))
print(a)
a[:,1,np.newaxis]

[[5 2 3 7 7]
 [4 1 3 9 9]
 [1 6 7 9 6]
 [9 9 3 9 5]
 [1 3 5 5 6]]


array([[2],
       [1],
       [6],
       [9],
       [3]])

# Slice the first 5 elements of an array.

In [40]:
a=np.random.randint(1,10,10)
print(a)
a[0:5]

[5 4 8 2 9 5 5 7 8 4]


array([5, 4, 8, 2, 9])

# Slice every second element of an array.

In [41]:
a=np.random.randint(1,10,10)
print(a)
a[::2]

[1 2 9 2 2 9 5 2 7 1]


array([1, 9, 2, 5, 7])

# Reverse an array using slicing.

In [42]:
a=np.random.randint(1,10,10)
print(a)
a[::-1]

[1 1 8 9 6 3 4 9 9 4]


array([4, 9, 9, 4, 3, 6, 9, 8, 1, 1])

# Extract the first two rows and last two columns of a 4×4 array

In [44]:
a=np.random.randint(1,10,(4,4))
print(a)
c=a[:2]
d=a[:,-2:]
print()
print(c)
print()
print(d)

[[9 7 3 1]
 [6 9 1 1]
 [1 6 3 6]
 [1 8 1 7]]

[[9 7 3 1]
 [6 9 1 1]]

[[3 1]
 [1 1]
 [3 6]
 [1 7]]


# Replace a slice of an array with another array.

In [48]:
a=np.array([1])
ar=np.array([4,5,6])
ar[2:]=a
print(ar)

[4 5 1]


# Find all elements greater than 10 in an array.

In [49]:
n=np.random.randint(1,30,10)
print(n)
b=n[n>10]
print(b)

[ 3 14 14  7 23 29 22 14 28  5]
[14 14 23 29 22 14 28]


# Find all even numbers in an array.

In [50]:
n=np.random.randint(1,30,10)
print(n)
even=n[n%2==0]
print(even)

[ 9 21  2  8 22 17  8  1 19 22]
[ 2  8 22  8 22]


# Filter all elements divisible by both 3 and 5.

In [51]:
n=np.random.randint(1,30,10)
print(n)
fi=n[(n%3==0)&(n%5==0)]
print(fi)

[25  7 16 15 23 25 10 18 17 10]
[15]


# Replace all negative numbers in an array with 0.

In [52]:

arr = np.array([3, -1, 5, -7, 2, -4])
arr[arr < 0] = 0
print(arr)


[3 0 5 0 2 0]


 # Extract elements using a list of indices.

In [54]:
arr = np.array([10, 20, 30, 40, 50])
indices=[0,2,4]
sel=arr[indices]
print(sel)

[10 30 50]


# Set all elements less than 5 to -1.

In [55]:
a=np.arange(1,10)
print(a)
a[a<5]=-1
print(a)

[1 2 3 4 5 6 7 8 9]
[-1 -1 -1 -1  5  6  7  8  9]


# Extract all elements where another array is greater than 50.

In [56]:
arr1 = np.array([10, 20, 30, 40, 50, 60, 70])
arr2 = np.array([45, 55, 35, 65, 25, 75, 80])
result=arr1[arr2>50]
print(result)

[20 40 60 70]


# Use np.where to find indices of elements > 10.

In [57]:
arr1 = np.array([10, 20, 30, 40, 50, 60, 70])
a=np.where(arr>10)
print(a)

(array([1, 2, 3, 4], dtype=int64),)


# Use boolean indexing to replace specific values.

In [62]:
arr1 = np.array([10, 20, 30, 40, 50, 60, 70])
arr=[0,1,2]
a=[1,2,3]
arr1[arr]=a
print(arr1)

[ 1  2  3 40 50 60 70]


# Count how many elements satisfy a condition

In [69]:
arr1 = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr1)
count=np.sum(arr1>50)
print(count)


[10 20 30 40 50 60 70]
2


# find mean row wise and cloumn wise brodcast

In [71]:
arr = np.random.randint(1, 100, (10, 10))
print(arr)
row_mean=arr.mean(axis=1)
row_bro=row_mean[:,np.newaxis]
print(row_bro)
col_mean=arr.mean(axis=0)
colbro=col_mean[np.newaxis,:]
print(col_mean)

[[68 13 15  6 45 74 86 98 15 96]
 [71 93 14 41  7 93 34 23 77 52]
 [59  8 41 16 73 67 17 32 83 84]
 [38 91 33 98 93 32 94 59 48 38]
 [77 83 16 85 30 52 95 21 34 95]
 [34 69 62 91 19 42  2 47 81 99]
 [98 32 89 73  4 46 77 26 50 29]
 [10 26 69 59 24 63 96 21 43 38]
 [90 89 23 40 94 15 63 48 79  5]
 [71 63 26 41 20  6 57 91 49 72]]
[[51.6]
 [50.5]
 [48. ]
 [62.4]
 [58.8]
 [54.6]
 [52.4]
 [44.9]
 [54.6]
 [49.6]]
[61.6 56.7 38.8 55.  40.9 49.  62.1 46.6 55.9 60.8]


# Add two arrays element-wise.

In [72]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=np.add(a,b)
print(c)

[2 4 6 8]


# Subtract two arrays element-wise

In [73]:
a=np.array([2,4,6,8,10])
b=np.array([1,2,3,4,5])
c=a-b
print(c)

[1 2 3 4 5]


# Multiply two arrays element-wise.

In [74]:
a=np.array([2,4,6,8,10])
b=np.array([1,2,3,4,5])
c=a*b
print(c)

[ 2  8 18 32 50]


# Divide two arrays element-wise.

In [75]:
arr = np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(arr)
b=np.max(arr)
c=arr/b
print(c)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
[[0.22222222 0.44444444 0.66666667]
 [0.11111111 1.         0.33333333]
 [0.55555556 0.77777778 0.22222222]]


# Raise each element to the power of 2.

In [76]:
arr = np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(arr)
arr2=arr**2
print(arr2)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
[[ 4 16 36]
 [ 1 81  9]
 [25 49  4]]


# Calculate the square root of each element

In [77]:
a=np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(a)
b=np.sqrt(a)
print(b)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
[[1.41421356 2.         2.44948974]
 [1.         3.         1.73205081]
 [2.23606798 2.64575131 1.41421356]]


# Compute the exponential of each element.

In [78]:
a=np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(a)
b=np.exp(a)
print(b)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
[[7.38905610e+00 5.45981500e+01 4.03428793e+02]
 [2.71828183e+00 8.10308393e+03 2.00855369e+01]
 [1.48413159e+02 1.09663316e+03 7.38905610e+00]]


# Compute the natural logarithm of each element.

In [79]:
a=np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(a)
b=np.log(a)
print(b)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
[[0.69314718 1.38629436 1.79175947]
 [0.         2.19722458 1.09861229]
 [1.60943791 1.94591015 0.69314718]]


# Compute the sum of all elements.

In [80]:
a=np.array([1, 2, 3, 4, 5])
print(a)
b=np.sum(a)
print(b)

[1 2 3 4 5]
15


# Compute the sum along rows or columns.

In [82]:
a=np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(a)
raw_sum=np.sum(a,axis=1)
print('row sum is',raw_sum)
col_sum=np.sum(a,axis=0)
print('column sum is',col_sum)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
row sum is [12 13 14]
column sum is [ 8 20 11]


# Find the mean of an array.

In [83]:
a=np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(a)
b=np.mean(a)
print(b)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
4.333333333333333


# Find the median of an array.

In [84]:
a=np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(a)
b=np.median(b)
print(b)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
4.333333333333333


# Find the standard deviation.

In [85]:
a=np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(a)
b=np.std(a)
print(b)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
2.494438257849294


# Find the variance.

In [86]:
a=np.array([[2, 4, 6],
                [1, 9, 3],
                [5, 7, 2]])
print(a)
b=np.var(a)
print(b)

[[2 4 6]
 [1 9 3]
 [5 7 2]]
6.222222222222222


# Find the minimum and maximum values.

In [87]:
ar=np.random.randint(1,50,(4,5))
print(ar)
m=np.min(ar)
ma=np.max(ar)
print(m)
print(ma)

[[40  9  1 18 22]
 [28 18 17  2  1]
 [ 4 20  3 37 22]
 [ 3 34 48 25  1]]
1
48


# Find the index of the minimum and maximum values.

In [88]:
ar=np.random.randint(1,50,(4,5))
print(ar)
a=np.argmin(ar)
print(a)
b=np.argmax(ar)
print(b)

[[37 10 19 14 26]
 [13 11 41 39 33]
 [ 4 48  4 18 25]
 [17  8 15  8 14]]
10
11


# Compute the cumulative sum.

In [89]:
ar=np.random.randint(1,50,(4,5))
print(ar)
c=np.cumsum(ar)
print(c)

[[17 14 39 48 23]
 [33 21 19  7  4]
 [42  7 44  8 41]
 [46 32 33 28  5]]
[ 17  31  70 118 141 174 195 214 221 225 267 274 318 326 367 413 445 478
 506 511]


# Compute the cumulative product.

In [90]:
ar=np.random.randint(1,50,size=10)
print(ar)
b=np.cumproduct(ar)
print(b)

[28 25 44 31  6 30 12 35 48  1]
[         28         700       30800      954800     5728800   171864000
  2062368000  -831564032 -1260367872 -1260367872]


# Find the percentile (e.g., 25th percentile).

In [98]:
ar=np.random.randint(1,50,size=10)
print(ar)
c=np.percentile(ar,25)
print(np.median(ar))
print(c)

[45 31  3 29  6 35 18 34 49 35]
32.5
20.75


# Compute correlation between two arrays.

In [99]:
ar=np.random.randint(1,50,size=10)
ar1=np.random.randint(1,50,size=10)
print(ar)
print(ar1)
c=np.corrcoef(ar,ar1)
print(c)

[ 4 10 22 13 32 43 48 15  1 32]
[25 45 16 33  8 29 45 33 18 19]
[[1.         0.08563478]
 [0.08563478 1.        ]]


# Create a 2×2 matrix and compute its determinant.

In [100]:
a=np.random.randint(1,10,(2,2))
print(a)
b=np.linalg.det(a)
print(b)

[[7 6]
 [1 7]]
43.0


# Compute the inverse of a 3×3 matrix.

In [101]:
a=np.random.randint(1,10,(3,3))
print(a)
b=np.linalg.inv(a)
print(b)

[[3 1 4]
 [6 8 5]
 [4 7 3]]
[[-1.22222222  2.77777778 -3.        ]
 [ 0.22222222 -0.77777778  1.        ]
 [ 1.11111111 -1.88888889  2.        ]]


# Compute the transpose of a matrix.

In [102]:
a=np.random.randint(1,10,(2,3))
print(a)
b=np.transpose(a)
print(b)

[[7 6 4]
 [7 6 9]]
[[7 7]
 [6 6]
 [4 9]]


# Compute matrix multiplication.

In [103]:
a=np.random.randint(1,10,(2,3))
b=np.random.randint(1,10,(3,2))
print(a)
print(b)
c=np.matmul(a,b)
print(c)

[[4 6 6]
 [5 6 5]]
[[2 9]
 [6 3]
 [4 6]]
[[68 90]
 [66 93]]


# Compute the dot product of two vectors.

In [104]:
a=np.random.randint(1,10,(2,3))
b=np.random.randint(1,10,(3,2))
print(a)
print(b)
c=np.dot(a,b)

[[8 4 8]
 [1 7 3]]
[[2 3]
 [9 7]
 [4 1]]


# Solve a linear system of equations 

In [105]:
A = np.array([[2, 1],
              [3, -1]])
B=np.array([8,5])
s=np.linalg.solve(A,B)
print(s)

[2.6 2.8]


# Find eigenvalues and eigenvectors.

In [112]:
a=np.random.randint(1,10,(4,4))
print(a)
c,b=np.linalg.eig(a)
print('eigan value',c)
print('eigan vector',b)


[[2 6 2 5]
 [5 2 9 6]
 [2 8 9 2]
 [2 4 2 5]]
eigan value [18.523584   -5.79516073  0.24851089  5.02306584]
eigan vector [[-0.38651079 -0.43391104  0.87049843  0.55025083]
 [-0.58201644  0.81170352  0.15688447  0.04935817]
 [-0.63804692 -0.35945855 -0.25274291 -0.64284783]
 [-0.3236702  -0.15377955 -0.3920979   0.53059822]]


# Compute the trace of a matrix.

In [115]:
a=np.random.randint(1,10,(4,4))
print(a)
b=np.trace(a)
print(b)

[[7 5 2 7]
 [8 1 5 9]
 [4 6 5 8]
 [1 8 7 9]]
22


# Compute the rank of a matrix.

In [116]:
a=np.random.randint(1,10,(3,4))
print(a)
b=np.linalg.matrix_rank(a)
print(b)

[[2 2 7 4]
 [2 7 3 4]
 [6 5 8 9]]
3


# Compute the norm of a vector.

In [118]:
a=np.array([1,2,3,4,5,6,7])
b=np.linalg.norm(a)
print(b)


11.832159566199232


# Generate 5 random integers between 0 and 10.

In [119]:
a=np.random.randint(1,10,(4,3))
print(a)

[[3 8 1]
 [4 5 7]
 [1 6 6]
 [6 3 1]]


In [120]:
a=np.random.random((4,3))
print(a)

[[0.74407382 0.35231126 0.61232552]
 [0.25504998 0.72981532 0.23235993]
 [0.93847244 0.87812684 0.26788264]
 [0.73603183 0.41086834 0.36620026]]


# Generate a 3×3 matrix with random numbers from normal distribution.

In [122]:
a=np.random.randn(3,3)
print(a)

[[ 2.37471078 -0.45486266 -0.44359957]
 [ 1.21973879 -0.74391587 -0.26356424]
 [-0.79431402  0.65066861 -1.92404351]]


# Generate a 3×3 matrix with random numbers from uniform distribution.

In [123]:
a=np.random.uniform(1,10,(4,3))
print(a)

[[4.55530406 7.22591692 2.90855798]
 [4.69219509 6.45817689 2.29044156]
 [9.2754025  8.46038117 5.78135877]
 [1.42049424 9.74827391 8.80964905]]


# Set a random seed for reproducibility.

In [127]:
np.random.seed(42)
a=np.random.randint(1,10,5)
print(a)

[7 4 8 5 7]


# Shuffle a 1D array randomly

In [128]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)

np.random.shuffle(arr)
print(arr)

Original array: [1 2 3 4 5 6 7 8 9]
[1 2 6 4 5 8 9 7 3]


# Randomly select 3 elements from an array.

In [132]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original array:", arr)
s=np.random.choice(arr,size=2,replace=False)
print(s)

Original array: [10 20 30 40 50 60 70]
[10 60]


# Generate 10 random numbers with mean 5 and std 2.Generate 10 random numbers with mean 5 and std 2.

In [133]:
mean=5
std=2
size=10
a=np.random.normal(loc=mean,scale=std,size=size)
print(a)

[5.4441578  3.464047   5.2849292  4.93069563 7.26867853 4.7905089
 3.9497543  8.82554254 0.94656077 7.23884722]


# Generate a 2×2 random matrix of integers divisible by 3.

In [134]:
m=3*np.random.randint(1,10,size=(2,2))
print(m)

[[15  6]
 [12 21]]


# Simulate rolling a dice 100 times.

In [135]:
n=100
d=np.random.randint(1,7,size=n)
print(d)

[4 5 3 6 1 4 2 4 2 6 6 6 2 4 6 5 2 2 4 2 2 6 4 6 6 4 1 6 5 5 2 5 2 1 4 4 4
 5 1 5 5 1 1 1 1 4 3 3 1 3 3 1 3 5 2 2 1 4 1 4 2 1 6 5 3 4 6 3 3 1 3 5 6 3
 1 5 2 6 3 1 2 2 4 5 3 1 4 5 4 6 5 5 3 5 4 5 3 3 6 4]


# Add a vector to each row of a matrix.

In [140]:
Arr3 = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
b=np.array([1,0,-1,2])
c=Arr3+b
print(c)

[[ 2  2  2  6]
 [ 6  6  6 10]
 [10 10 10 14]]


# Multiply a vector with each column of a matrix

In [142]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
b=np.array([1,2,3])
c=A*b.reshape(-1,1)
print(A)
print(b)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3]
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


# Subtract the mean of each row from the row.

In [143]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
print(a)
row_mean=a.mean(axis=1).reshape(-1,1)
c=a-row_mean
print(row_mean)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2.5]
 [ 6.5]
 [10.5]]
[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


# Divide each row by its maximum value.

In [144]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
print(a)
b=a.max(axis=1).reshape(-1,1)
c=a/b
print(b)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 4]
 [ 8]
 [12]]
[[0.25       0.5        0.75       1.        ]
 [0.625      0.75       0.875      1.        ]
 [0.75       0.83333333 0.91666667 1.        ]]


# Compute element-wise exponential of a matrix minus its row mean

In [145]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])
print(a)
b=a.mean(axis=1).reshape(-1,1)
c=a-c
d=np.exp(c)
print(b)
print(c)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2.5]
 [ 6.5]
 [10.5]]
[[ 0.75        1.5         2.25        3.        ]
 [ 4.375       5.25        6.125       7.        ]
 [ 8.25        9.16666667 10.08333333 11.        ]]
[[2.11700002e+00 4.48168907e+00 9.48773584e+00 2.00855369e+01]
 [7.94398396e+01 1.90566268e+02 4.57144713e+02 1.09663316e+03]
 [3.82762582e+03 9.57266257e+03 2.39406549e+04 5.98741417e+04]]


# Compare performance of a for-loop vs vectorized operation

In [146]:
import numpy as np
import time

# Large array
arr = np.random.rand(1000000)

# -----------------------------
# 1️⃣ Using a for-loop
# -----------------------------
start_time = time.time()

squares_loop = np.zeros_like(arr)
for i in range(len(arr)):
    squares_loop[i] = arr[i] ** 2

end_time = time.time()
print("For-loop time:", end_time - start_time, "seconds")

# -----------------------------
# 2️⃣ Using vectorized operation
# -----------------------------
start_time = time.time()

squares_vectorized = arr ** 2

end_time = time.time()
print("Vectorized time:", end_time - start_time, "seconds")

# -----------------------------
# Verify results are same
# -----------------------------
print("Results are equal:", np.allclose(squares_loop, squares_vectorized))


For-loop time: 0.45852136611938477 seconds
Vectorized time: 0.0 seconds
Results are equal: True


# Implement a vectorized linear regression prediction.

In [147]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 0, 2],
              [0, 1, 1]])
w = np.array([0.2, 0.5, 0.1])
b=0.5
y=x.dot(w)+b
print(y)

[2.  4.4 6.8 0.9 1.1]


# Compute the pairwise distance matrix between points.

In [148]:
points = np.array([[0, 0],
                   [1, 1],
                   [2, 2],
                   [3, 3]])
di=points[:,np.newaxis,:]-points[np.newaxis,:,:]
c=np.sqrt(np.sum(di**2,axis=2))
print(c)

[[0.         1.41421356 2.82842712 4.24264069]
 [1.41421356 0.         1.41421356 2.82842712]
 [2.82842712 1.41421356 0.         1.41421356]
 [4.24264069 2.82842712 1.41421356 0.        ]]


# Apply a function to each row without using loops.

In [151]:
A=np.array([1,2,3,4,5])
result_vec = np.sum(A**2)
print("Vectorized sum of squares:", result_vec)


Vectorized sum of squares: 55


# Normalize a 2D array (min-max scaling) using broadcasting.

In [152]:
a=np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a)
b=a.min()
c=a.max()
d=(a-b)/c-b
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.         -0.88888889 -0.77777778]
 [-0.66666667 -0.55555556 -0.44444444]
 [-0.33333333 -0.22222222 -0.11111111]]


# concatenate two array horizontly

In [153]:
a=np.arange(1,10)
b=np.arange(1,10)
print(a)
print(b)
c=np.stack((a,b))
print(c)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


# Split an array into 3 equal parts.

In [154]:
a=np.arange(1,10)
b=np.split(a,3)
print(b)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


# Stack two arrays along a new axis.

In [156]:
a=np.arange(1,10)
b=np.arange(1,10)
c=np.stack((a,b),axis=1)
print(c)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]


In [157]:
arr = np.array([1, 2, 3])
repeated = np.repeat(arr, 3)
print(repeated)

[1 1 1 2 2 2 3 3 3]


# Tile an array 2×2 times.

In [158]:
a=np.array([1,2])
c=np.tile(a,(2,2))
print(c)

[[1 2 1 2]
 [1 2 1 2]]


In [159]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)
arr_row_deleted = np.delete(arr, 1, axis=0)
print("After deleting row 1:\n", arr_row_deleted)
arr_col_deleted = np.delete(arr, 2, axis=1)
print("After deleting column 2:\n", arr_col_deleted)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
After deleting row 1:
 [[1 2 3]
 [7 8 9]]
After deleting column 2:
 [[1 2]
 [4 5]
 [7 8]]


In [168]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)

b=np.insert(arr,1,[17,3,4],axis=0)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [17  3  4]
 [ 4  5  6]
 [ 7  8  9]]


In [172]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)
arr1 = np.array([[1, 2, 3],
                [4, 11, 12],
                [7, 14, 15]])
print(arr1)
c=np.intersect1d(arr,arr1)
print('comomen element',c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 11 12]
 [ 7 14 15]]
comomen element [1 2 3 4 7]


In [176]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)
arr1 = np.array([[1, 2, 3],
                [4, 11, 12],
                [7, 14, 15]])
print(arr1)
c=np.all(np.isin(arr,arr1))
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 11 12]
 [ 7 14 15]]
False


In [194]:
a=np.array([1,np.nan,5,np.nan,5,7,6])
print(a)
replace=np.nan_to_num(a,nan=3)
print(replace)


[ 1. nan  5. nan  5.  7.  6.]
[1. 3. 5. 3. 5. 7. 6.]


In [195]:
a=np.array([1,np.nan,5,np.nan,5,7,6])
print(a)
a[np.isnan(a)]=1
print(a)

[ 1. nan  5. nan  5.  7.  6.]
[1. 1. 5. 1. 5. 7. 6.]


In [200]:
a=np.random.randint(1,10,(5,5))

print(a)
c=np.diag(np.fliplr(a))
print(c)

[[5 8 5 4 5]
 [6 1 6 9 8]
 [7 6 7 6 3]
 [6 7 2 3 3]
 [6 1 7 2 9]]
[5 9 7 7 6]


In [201]:
a=np.array([[1,2,2,2],
         [4,5,5,2]])
np.unique(a)

array([1, 2, 4, 5])

In [203]:
a=np.array([1,2,2,3])
b=np.array([1,2,4,5])
c=np.intersect1d(a,b)
print(c)

[1 2]
