# Convert a 1D array into 2D (3×4).

In [2]:
import numpy as np

In [3]:
arr=np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Flatten a matrix into 1D.

In [12]:
arr1=np.arange(27).reshape(3,3,3)
print(arr1)
arr1.flatten()

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Transpose a 2D array.

In [14]:
arr2=np.arange(30).reshape(5,6)
ar=np.transpose(arr2)
print(ar)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [16]:
arr2.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# Create an array of numbers 1–12 and reshape it into a 3×4 matrix.

In [19]:
aray=np.arange(1,13).reshape(3,4)
print(aray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Transpose a 2×3 matrix into a 3×2 matrix.

In [25]:
a=np.zeros((2,3),dtype=int)
print(a)
b=np.transpose(a)
print(b)

[[0 0 0]
 [0 0 0]]
[[0 0]
 [0 0]
 [0 0]]


# Reshape numbers 0–29 into a 6×5 matrix and extract the 3rd column.

In [34]:
ar=np.arange(30).reshape(6,5)
print(ar)
print(ar[:,2:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 2]
 [ 7]
 [12]
 [17]
 [22]
 [27]]


# Flatten a 3×3 matrix and sort elements in descending order.

In [43]:
a=np.random.randint(1,10,(3,3))
print(a)
b=a.flatten()
print(b)
print(b[::-1])

[[5 3 8]
 [3 1 2]
 [8 9 9]]
[5 3 8 3 1 2 8 9 9]
[9 9 8 2 1 3 8 3 5]


# Create an 8×8 checkerboard pattern using only zeros() and slicing.

In [98]:
a=np.zeros((8,8),dtype=int)
print(a)
print()
a[0::2,::2]=1
a[1::2,1::2]=1
print(a)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
