# Slice a 2D array into sub-arrays.

In [2]:
import numpy as np

In [3]:
arr=np.arange(1,21)
arr1=arr.reshape(5,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [4]:
sub=arr1[1:3,1:4]
print(sub)

[[ 6  7  8]
 [10 11 12]]


# Find row-wise max, column-wise min.

In [5]:
a=np.linspace(1,101,20)
b=a.reshape(4,5)
print(b)

[[  1.           6.26315789  11.52631579  16.78947368  22.05263158]
 [ 27.31578947  32.57894737  37.84210526  43.10526316  48.36842105]
 [ 53.63157895  58.89473684  64.15789474  69.42105263  74.68421053]
 [ 79.94736842  85.21052632  90.47368421  95.73684211 101.        ]]


In [6]:
min_r=np.max(b,axis=0)
print(min_r)
max_c=np.max(b,axis=1)
print(max_c)

[ 79.94736842  85.21052632  90.47368421  95.73684211 101.        ]
[ 22.05263158  48.36842105  74.68421053 101.        ]


# Perform broadcasting 

In [7]:
a=np.arange(1,7)
b=a.reshape(2,3)
print(b)
c=np.array([[1,2]])
print(c)
print(b+c)

[[1 2 3]
 [4 5 6]]
[[1 2]]


ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

observation: there is no brodcasting whith 1D array and 2D array

In [34]:
a=np.arange(25,33)
b=a.reshape(2,4)
print(b+5)

[[30 31 32 33]
 [34 35 36 37]]


In [40]:
a=np.arange(1,10)
b=a.reshape(3,3)
c=np.array([2,5,10])

print(b+c)

[[ 3  7 13]
 [ 6 10 16]
 [ 9 13 19]]


In [ ]:
student=np.array([
    [20,30,40,50],
    [30,30,30,30],
    [50,20,30,40],
    [20,50,50,30],
    [40,40,30,20]
])
s=np.sum(student,axis=1)
s

# Slice the first 5 elements from an array of numbers 1–20.

In [46]:
a=np.arange(1,21)
a[0:5]

array([1, 2, 3, 4, 5])

# Extract the diagonal elements of a 4×4 matrix.


In [52]:
arr=np.arange(1,17)
arr1=arr.reshape(4,4)
print(arr1)
diag=np.diag(arr1)
print(diag)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]


In [54]:
arr=np.arange(1,17)
arr1=arr.reshape(4,4)
print(arr1)
diag=np.diag(arr1,k=1)
print(diag)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2  7 12]


In [55]:
arr=np.arange(1,17)
arr1=arr.reshape(4,4)
print(arr1)
diag=np.diag(arr1,k=-1)
print(diag)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 5 10 15]


In [56]:
np.diag(np.diag(arr1))


array([[ 1,  0,  0,  0],
       [ 0,  6,  0,  0],
       [ 0,  0, 11,  0],
       [ 0,  0,  0, 16]])

In [58]:
arr1.diagonal(2)

array([3, 8])

# Replace all negative values in an array with 0.

In [63]:
a=np.arange(-5,5)
print(a)
a.size
b=a.reshape(2,5)
print(b)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[[-5 -4 -3 -2 -1]
 [ 0  1  2  3  4]]


In [65]:
b[b<0]=0
print(b)

[[0 0 0 0 0]
 [0 1 2 3 4]]


# Create a 5×5 random integer array (1–50) and replace all values greater than 25 with 99.

In [68]:
ar=np.random.randint(1,51,(5,5))
print(ar)

[[39 15 17 19  8]
 [38 16 41 35 50]
 [ 5 43 11 48  9]
 [12 36 49 26 31]
 [42 26 27 12 41]]


In [69]:
ar[ar>25]=99
print(ar)

[[99 15 17 19  8]
 [99 16 99 99 99]
 [ 5 99 11 99  9]
 [12 99 99 99 99]
 [99 99 99 12 99]]
