# Create 1D, 2D arrays with array() and arange().



## With array

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr1=np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [4,6,8,6,4],
])
print(type(arr))
print(arr1)
arr1.shape
arr1.ndim

<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [2 3 4 5 6]
 [4 6 8 6 4]]


2

## Arange

In [4]:
ar=np.arange(1,11)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
ar1=np.arange(1,11)
ar1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Generate arrays of zeros/ones.

In [6]:
ar1=np.zeros((3,4))
print(ar1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
ar=np.ones((4,3))
print(ar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Check array shape, size, and dtype.

In [8]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(3, 3)
9
int64


# Create a NumPy array of numbers 1–10.

In [9]:
ary=np.arange(1,10)
print(ary)

[1 2 3 4 5 6 7 8 9]


# Generate an array of even numbers between 20 and 40.

In [10]:
ar=np.arange(20,41,2)
print(ar)

[20 22 24 26 28 30 32 34 36 38 40]


# Create an array of 20 random integers (1–50) and extract only the odd numbers.

In [11]:
ar=np.random.randint(1,50,20)
odd=ar[ar%2!=0]
print(odd)


[ 5 35 49 23  1 11  1  1 47 41 11  5 29  3 31]


# Compare memory usage of a Python list vs a NumPy array with 1000 element

In [12]:
import sys


py_list = list(range(1000))
print("List size:", sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list))


np_array = np.arange(1000, dtype=np.int32)
print("NumPy array size:", np_array.nbytes)


List size: 36056
NumPy array size: 4000


# Reshape a NumPy array of numbers 1–36 into a 6×6 matrix

In [13]:
a=np.arange(1,37)
a.size
arr=a.reshape(6,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


# Create a 10×10 array and set the border elements to 1, inner elements to 0.

In [24]:
arr=np.zeros((10,10))
arr[0,:]=1
arr[9,:]=1
arr[:,0]=1
arr[:,9]=1
print(arr)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
