# Stack two arrays vertically and horizontally.

In [1]:
import numpy as np

In [2]:
a=np.arange(12).reshape(4,3)
b=np.arange(12,24).reshape(4,3)
c=np.hstack((a,b))
d=np.vstack((a,b))
print(d)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[ 0  1  2 12 13 14]
 [ 3  4  5 15 16 17]
 [ 6  7  8 18 19 20]
 [ 9 10 11 21 22 23]]


# Split a 1D array into equal parts.

In [3]:
a=np.arange(20)
np.split(a,4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

# Demonstrate shallow vs deep copy.

In [11]:
a = np.array([1, 2, 3, 4, 5])
print("Original a:", a)

b=a.view()
b[0]=25
print("\nAfter modifying b (shallow copy):")
print("a:", a)
print("b:", b)

c=a.copy()
c[1]=200
print("\nAfter modifying c (deep copy):")
print("a:", a)
print("c:", c)

Original a: [1 2 3 4 5]

After modifying b (shallow copy):
a: [25  2  3  4  5]
b: [25  2  3  4  5]

After modifying c (deep copy):
a: [25  2  3  4  5]
c: [ 25 200   3   4   5]


# Concatenate two arrays [1,2,3] and [4,5,6].

In [15]:
a=np.arange(1,4)
b=np.arange(4,7)
arr=np.concatenate((a,b))
print(arr)

[1 2 3 4 5 6]


# Stack two 3×3 identity matrices vertically

In [22]:
a=np.identity((3),dtype=int)
b=np.identity(3)
print(a)
print(b)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
v_array=np.vstack((a,b))
print(v_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Split an array of size 20 into 4 equal chunks.

In [24]:
arr=np.arange(20)
new=np.split(arr,4)
print(new)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


# Show with code how modifying a .view() changes the original array but .copy()does not.

## view()

In [29]:
a=np.array([12,13,14,15])
b=a.view()
b[1]=3
print(a)
print(b)

[12  3 14 15]
[12  3 14 15]


## copy()

In [33]:
a=np.array([12,13,14,15])
b=a.copy()
b[1]=0
print(a)
print(b)

[12 13 14 15]
[12  0 14 15]


# create two arrays of shape (2×3) and horizontally stack them into a (2×6) array.

In [48]:
a=np.arange(1,7).reshape(2,3)
c=np.arange(7,13).reshape(2,3)
print(a)
b=np.hstack((a,c))
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)
